// Native screen definitions. UI is separate from trusted data providers.
export const features = {
  'Academic Report': {
    title: 'Every little step adds up.',
    subtitle: 'Published academic progress',
    type: 'report',
    filters: ['Subject', 'Term', 'Session'],
    metrics: ['Overall score', 'Attendance', 'Completed work'],
    icon: '📊',
  },
  'Personal & Behaviour Report': {
    title: 'Growing beyond the classroom.',
    subtitle: 'Personal development and behaviour',
    type: 'report',
    filters: ['Month', 'Session'],
    metrics: ['Participation', 'Teamwork', 'Responsibility'],
    icon: '🌱',
  },
  'Monthly Feedback': {
    title: 'A little feedback. A lot of growth.',
    subtitle: 'Academic and personal teacher feedback',
    type: 'report',
    filters: ['Month', 'Teacher'],
    metrics: ['Academic', 'Personal', 'Published'],
    icon: '💬',
  },
  'Student Progress Tracking': {
    title: 'See the whole learning journey.',
    subtitle: 'Student record and progress history',
    type: 'report',
    filters: ['Subject', 'Period'],
    metrics: ['Attendance', 'Assignments', 'Latest result'],
    icon: '🌟',
  },
  'Academic Calendar': {
    title: 'Good days, planned ahead.',
    subtitle: 'Academic dates, examinations and holidays',
    type: 'calendar',
    filters: ['Month', 'Year'],
    icon: '📅',
  },
  'School Events': {
    title: 'Make room for memorable moments.',
    subtitle: 'Published school events',
    type: 'events',
    filters: ['Type', 'Month'],
    action: 'Register',
    icon: '🎉',
  },
  'Sports & Activities': {
    title: 'A little teamwork goes a long way.',
    subtitle: 'Sports, clubs and school activities',
    type: 'events',
    filters: ['Activity', 'Month'],
    action: 'Register',
    icon: '🏅',
  },
  'Track My Child': {
    title: 'A little peace of mind.',
    subtitle: 'Confirmed school and transport events',
    type: 'travel',
    metrics: ['Last confirmed event', 'Trip status', 'GPS freshness'],
    icon: '🚌',
  },
  'Travel History': {
    title: 'Every journey has a story.',
    subtitle: 'Boarding, drop-off and travel exceptions',
    type: 'list',
    filters: ['From date', 'To date', 'Child'],
    icon: '🚌',
  },
  'Transport & Alerts': {
    title: 'A calmer journey to school.',
    subtitle: 'Assigned route, stop and transport notices',
    type: 'list',
    filters: ['Child'],
    icon: '🚏',
  },
  'Pickup & Early Exit': {
    title: 'Safe hands, every time.',
    subtitle: 'Approved pickup persons and early exit requests',
    type: 'form',
    fields: [
      'Child',
      'Pickup person',
      'Relationship',
      'Requested date',
      'Reason',
    ],
    action: 'Request early exit',
    icon: '🛡',
  },
  'PTM & Appointments': {
    title: 'Let’s make time to talk.',
    subtitle: 'Teacher and school appointments',
    type: 'appointments',
    fields: ['Child', 'Teacher', 'Date', 'Reason'],
    action: 'Request appointment',
    icon: '🗓',
  },
  'Documents & Consent': {
    title: 'The important things, kept together.',
    subtitle: 'School documents and versioned consent',
    type: 'documents',
    filters: ['Child', 'Document type'],
    action: 'Open document',
    icon: '📁',
  },
  Messages: {
    title: 'A good conversation starts here.',
    subtitle: 'Verified school and assigned-teacher threads',
    type: 'messages',
    fields: ['Recipient', 'Subject', 'Message'],
    action: 'Send message',
    icon: '✉',
  },
  Helpdesk: {
    title: 'How can we help?',
    subtitle: 'School support tickets and complaints',
    type: 'form',
    fields: ['Category', 'Subject', 'Message'],
    action: 'Create ticket',
    icon: '🛟',
  },
  Settings: {
    title: 'Make this space your own.',
    subtitle: 'Preferences, accessibility and account details',
    type: 'settings',
    icon: '⚙',
  },
  'Online Payment': {
    title: 'A simpler way to settle up.',
    subtitle: 'Invoice payment and provider confirmation',
    type: 'form',
    fields: ['Invoice ID', 'Amount', 'Payment method'],
    action: 'Continue to payment',
    icon: '💳',
  },
  'Installment Requests': {
    title: 'A plan that works for you.',
    subtitle: 'Installment and fee assistance requests',
    type: 'form',
    fields: ['Invoice ID', 'Requested installments', 'Reason'],
    action: 'Send request',
    icon: '▤',
  },
  'Learning Resources': {
    title: 'Big ideas start with curious minds.',
    subtitle: 'Subjects, lessons and approved resources',
    type: 'resources',
    filters: ['Subject', 'Resource type'],
    icon: '📚',
  },
  'Live Classroom': {
    title: 'Your classroom, wherever you are.',
    subtitle: 'Authorized live lessons',
    type: 'classroom',
    action: 'Join class',
    icon: '🎥',
  },
  'Recorded Lessons': {
    title: 'Press play on a little progress.',
    subtitle: 'Assigned recordings and viewing progress',
    type: 'resources',
    filters: ['Subject', 'Teacher'],
    action: 'Open recording',
    icon: '▶',
  },
  'Catch-up Workspace': {
    title: 'Find your rhythm again.',
    subtitle: 'Missed work and catch-up learning',
    type: 'list',
    filters: ['Subject', 'Status'],
    icon: '🌤',
  },
  'Notes & Flashcards': {
    title: 'Small notes. Big ideas.',
    subtitle: 'Your study notes and revision cards',
    type: 'notes',
    fields: ['Subject', 'Title', 'Note'],
    action: 'Save note',
    icon: '📝',
  },
  'AI Tutor': {
    title: 'Curiosity is always welcome.',
    subtitle: 'Learning questions and guided explanations',
    type: 'tutor',
    fields: ['Question'],
    action: 'Ask tutor',
    icon: '✨',
  },
  Quiz: {
    title: 'Time for a tiny challenge.',
    subtitle: 'Assigned practice and assessments',
    type: 'quiz',
    icon: '💡',
  },
  'Revision Planner': {
    title: 'A little plan for a big goal.',
    subtitle: 'Study sessions and revision targets',
    type: 'form',
    fields: ['Subject', 'Topic', 'Study date', 'Duration'],
    action: 'Save study session',
    icon: '🎯',
  },
  'Library & Services': {
    title: 'There’s always more to discover.',
    subtitle: 'School library, clubs and student services',
    type: 'list',
    filters: ['Category'],
    icon: '📖',
  },
  'Student Ledger': {
    title: 'Every balance tells a clear story.',
    subtitle: 'Branch-scoped student transactions',
    type: 'report',
    filters: ['Student ID', 'From date', 'To date'],
    metrics: ['Confirmed paid', 'Pending', 'Balance due'],
    icon: '▥',
  },
  'Advance Balances': {
    title: 'Keep every rupee accounted for.',
    subtitle: 'Student advances and allocations',
    type: 'report',
    filters: ['Student ID'],
    metrics: ['Available advance', 'Allocated', 'Remaining'],
    icon: '💰',
  },
  'Finance Requests': {
    title: 'Clear requests. Clear decisions.',
    subtitle: 'Installment, discount and refund approvals',
    type: 'form',
    fields: ['Student ID', 'Invoice ID', 'Request type', 'Amount', 'Reason'],
    action: 'Request approval',
    icon: '☑',
  },
  'Voucher Scan': {
    title: 'Scan. Check. Confirm.',
    subtitle: 'Voucher lookup and verification',
    type: 'scanner',
    fields: ['Voucher code'],
    action: 'Verify voucher',
    icon: '▦',
  },
  'Exceptions & Closing': {
    title: 'End the day with everything in order.',
    subtitle: 'Exceptions, reconciliation and closing review',
    type: 'report',
    filters: ['Date', 'Payment method'],
    metrics: ['Confirmed collection', 'Unmatched', 'Drawer balance'],
    icon: '🧾',
  },
  'Receipt Details': {
    title: 'Every payment, properly recorded.',
    subtitle: 'Confirmed receipt and invoice details',
    type: 'receipt',
    fields: ['Payment ID'],
    action: 'Find receipt',
    icon: '🧾',
  },
};
export const extraPages = {
  Parent: [
    'Academic Report',
    'Personal & Behaviour Report',
    'Monthly Feedback',
    'Student Progress Tracking',
    'Academic Calendar',
    'School Events',
    'Sports & Activities',
    'Track My Child',
    'Travel History',
    'Transport & Alerts',
    'Pickup & Early Exit',
    'PTM & Appointments',
    'Documents & Consent',
    'Online Payment',
    'Installment Requests',
    'Receipt Details',
    'Messages',
    'Helpdesk',
    'Settings',
  ],
  Student: [
    'Learning Resources',
    'Live Classroom',
    'Recorded Lessons',
    'Catch-up Workspace',
    'Notes & Flashcards',
    'AI Tutor',
    'Quiz',
    'Revision Planner',
    'Academic Report',
    'Monthly Feedback',
    'Academic Calendar',
    'School Events',
    'Sports & Activities',
    'Library & Services',
    'Messages',
    'Helpdesk',
    'Settings',
  ],
  Finance: [
    'Student Ledger',
    'Advance Balances',
    'Finance Requests',
    'Voucher Scan',
    'Exceptions & Closing',
    'Receipt Details',
    'Messages',
    'Helpdesk',
    'Settings',
  ],
};
export const staffFeatures = {};
const staffCopy = {
  Teacher: {
    Home: [
      'A little teaching. A lot of possibility.',
      'Your classes, lessons and school day',
      'report',
    ],
    Classes: [
      'Your classroom, all together.',
      'Assigned classes and student rosters',
      'list',
    ],
    Attendance: [
      'Every student counts.',
      'Class attendance and corrections',
      'form',
    ],
    Homework: [
      'Small tasks. Big progress.',
      'Assigned homework and submissions',
      'list',
    ],
    Applications: [
      'Keep every request moving.',
      'Student and parent requests for your class',
      'list',
    ],
    Inbox: [
      'Your school updates, together.',
      'Assigned-school notifications',
      'list',
    ],
  },
  Principal: {
    Home: [
      'A calmer school day starts here.',
      'School overview and pending reviews',
      'report',
    ],
    Teachers: [
      'Good teaching starts with a good team.',
      'School teachers and assignments',
      'list',
    ],
    Reports: [
      'See the whole school picture.',
      'Branch-scoped academic and school reports',
      'report',
    ],
    Applications: [
      'Clear requests. Thoughtful decisions.',
      'Teacher applications and approval history',
      'list',
    ],
    Inbox: [
      'The updates that matter.',
      'School notifications and shared records',
      'list',
    ],
  },
  'Super Admin': {
    Home: [
      'A little overview. A lot of clarity.',
      'Assigned schools and system health',
      'report',
    ],
    Schools: [
      'Every school, connected.',
      'Assigned schools and branches',
      'list',
    ],
    Users: [
      'The right access for the right people.',
      'School users and assigned roles',
      'list',
    ],
    Events: [
      'Make room for memorable moments.',
      'School events and announcements',
      'events',
    ],
    Reports: [
      'Clear records across your schools.',
      'Permitted school and branch reports',
      'report',
    ],
    Applications: [
      'Keep school requests moving.',
      'Principal applications and decisions',
      'list',
    ],
    Inbox: [
      'Your school updates, together.',
      'Permitted school notifications',
      'list',
    ],
  },
};
Object.entries(staffCopy).forEach(([role, definitions]) => {
  staffFeatures[role] = {};
  Object.entries(definitions).forEach(([page, [title, subtitle, type]]) => {
    staffFeatures[role][page] = {
      title,
      subtitle,
      type,
      icon: role === 'Teacher' ? '👩‍🏫' : '🏫',
      filters:
        type === 'report' ? ['Period', 'Class / branch'] : ['Search', 'Status'],
      metrics:
        type === 'report'
          ? ['Attendance', 'Pending reviews', 'Published records']
          : undefined,
      fields:
        type === 'form'
          ? ['Class ID', 'Student ID', 'Date', 'Status', 'Reason']
          : undefined,
      action: type === 'form' ? 'Save attendance' : undefined,
    };
  });
});
features['Student Fees'] = {
  title: 'Your fees, clearly explained.',
  subtitle: 'Your invoices, confirmed payments and due balance',
  type: 'report',
  metrics: ['Confirmed paid', 'Pending', 'Due'],
  icon: '▤',
};
features['Travel Status'] = {
  ...features['Track My Child'],
  title: 'Your school journey at a glance.',
  subtitle: 'Your confirmed boarding and drop-off status',
};
features['Finance Reports'] = {
  title: 'Find the report you actually need.',
  subtitle: 'Permitted branch collection reports',
  type: 'report',
  filters: ['From date', 'To date'],
  metrics: ['Confirmed collection', 'Outstanding', 'Pending'],
  icon: '▥',
};
features['Attendance Calendar'] = {
  title: 'Every school day counts.',
  subtitle: 'Confirmed attendance by date',
  type: 'calendar',
  icon: '✓',
};
features['Leave Request'] = {
  title: 'Let your school know.',
  subtitle: 'Leave application to the assigned class teacher',
  type: 'form',
  fields: ['From date', 'To date', 'Reason'],
  action: 'Send leave request',
  icon: '✎',
};
extraPages.Student.push(
  'Student Fees',
  'Travel Status',
  'Attendance Calendar',
  'Leave Request',
);
extraPages.Parent.push(
  'Recorded Lessons',
  'Catch-up Workspace',
  'Attendance Calendar',
  'Leave Request',
);
extraPages.Finance.push('Finance Reports');
