import React from 'react';
import { Image } from 'react-native';

export const iconSources = {
  home: require('./assets/icons/home.png'),
  users: require('./assets/icons/users.png'),
  'calendar-check': require('./assets/icons/calendar-check.png'),
  calendar: require('./assets/icons/calendar.png'),
  book: require('./assets/icons/book.png'),
  homework: require('./assets/icons/homework.png'),
  graduation: require('./assets/icons/graduation.png'),
  chart: require('./assets/icons/chart.png'),
  clipboard: require('./assets/icons/clipboard.png'),
  'file-pen': require('./assets/icons/file-pen.png'),
  card: require('./assets/icons/card.png'),
  receipt: require('./assets/icons/receipt.png'),
  scan: require('./assets/icons/scan.png'),
  message: require('./assets/icons/message.png'),
  bell: require('./assets/icons/bell.png'),
  bus: require('./assets/icons/bus.png'),
  party: require('./assets/icons/party.png'),
  trophy: require('./assets/icons/trophy.png'),
  folder: require('./assets/icons/folder.png'),
  settings: require('./assets/icons/settings.png'),
  help: require('./assets/icons/help.png'),
  logout: require('./assets/icons/logout.png'),
  video: require('./assets/icons/video.png'),
  play: require('./assets/icons/play.png'),
  pin: require('./assets/icons/pin.png'),
  shield: require('./assets/icons/shield.png'),
  sparkle: require('./assets/icons/sparkle.png'),
  clock: require('./assets/icons/clock.png'),
  school: require('./assets/icons/school.png'),
  wallet: require('./assets/icons/wallet.png'),
  file: require('./assets/icons/file.png'),
  menu: require('./assets/icons/menu.png'),
  more: require('./assets/icons/more.png'),
  close: require('./assets/icons/close.png'),
  notes: require('./assets/icons/notes.png'),
  target: require('./assets/icons/target.png'),
  refresh: require('./assets/icons/refresh.png'),
  download: require('./assets/icons/download.png'),
  search: require('./assets/icons/search.png'),
  check: require('./assets/icons/check.png'),
  inbox: require('./assets/icons/inbox.png'),
  star: require('./assets/icons/star.png'),
  chevron: require('./assets/icons/chevron.png'),
  'chevron-down': require('./assets/icons/chevron-down.png'),
};

export const pageIconNames = {
  Home: 'home',
  Overview: 'home',
  Dashboard: 'home',
  'My children': 'users',
  'My Children': 'users',
  Students: 'users',
  Users: 'users',
  Teachers: 'users',
  Classes: 'users',
  Attendance: 'calendar-check',
  'Attendance Calendar': 'calendar-check',
  Timetable: 'calendar',
  'Academic Calendar': 'calendar',
  Calendar: 'calendar',
  'PTM & Appointments': 'calendar',
  Learning: 'book',
  'Learning Resources': 'book',
  'Library & Services': 'book',
  Homework: 'homework',
  Results: 'graduation',
  'Latest result': 'graduation',
  Progress: 'chart',
  Reports: 'chart',
  'Academic Report': 'chart',
  'Student Progress Tracking': 'chart',
  'Finance Reports': 'chart',
  'Collection report': 'chart',
  Collection: 'chart',
  'Personal & Behaviour Report': 'shield',
  'Monthly Feedback': 'message',
  'Teachers DLP': 'clipboard',
  DLP: 'clipboard',
  Applications: 'file-pen',
  'Leave Request': 'file-pen',
  Fees: 'card',
  'Student Fees': 'card',
  'Online Payment': 'card',
  Payments: 'card',
  'Payment entry': 'card',
  Invoices: 'receipt',
  Receipts: 'receipt',
  'Receipt Details': 'receipt',
  'Payment history': 'receipt',
  'Outstanding dues': 'wallet',
  Outstanding: 'wallet',
  'Fee due': 'wallet',
  'Fee Due': 'wallet',
  'Advance Balances': 'wallet',
  'Drawer balance': 'wallet',
  'Finance Requests': 'file-pen',
  'Installment Requests': 'file-pen',
  'Pending verification': 'clock',
  Pending: 'clock',
  'Voucher verification': 'shield',
  'Voucher Scan': 'scan',
  'Student Ledger': 'notes',
  'Exceptions & Closing': 'clipboard',
  'Student search': 'search',
  Messages: 'message',
  Inbox: 'inbox',
  Notifications: 'bell',
  'Notification Center': 'bell',
  Transport: 'bus',
  'Travel Status': 'bus',
  'Travel History': 'clock',
  'Transport & Alerts': 'bus',
  'Track My Child': 'pin',
  'Pickup & Early Exit': 'shield',
  Events: 'party',
  'School Events': 'party',
  'Sports & Activities': 'trophy',
  Sports: 'trophy',
  'Documents & Consent': 'folder',
  Documents: 'folder',
  Settings: 'settings',
  Helpdesk: 'help',
  Logout: 'logout',
  'Sign out': 'logout',
  'Recorded Lessons': 'play',
  'Live Classroom': 'video',
  'Catch-up Workspace': 'refresh',
  'Notes & Flashcards': 'notes',
  'AI Tutor': 'sparkle',
  Quiz: 'help',
  'Revision Planner': 'target',
  Schools: 'school',
  Parent: 'users',
  Student: 'graduation',
  Finance: 'wallet',
  Teacher: 'book',
  Principal: 'school',
  'Super Admin': 'shield',
};

export function getPageIconName(name) {
  return pageIconNames[name] || (iconSources[name] ? name : 'file');
}

export default function PageIcon({
  name = 'file',
  size = 24,
  color = '#4857B5',
  style,
  accessibilityLabel,
}) {
  return (
    <Image
      source={iconSources[getPageIconName(name)]}
      resizeMode="contain"
      accessible={!!accessibilityLabel}
      accessibilityLabel={accessibilityLabel}
      importantForAccessibility={accessibilityLabel ? 'yes' : 'no'}
      fadeDuration={0}
      style={[{ width: size, height: size, tintColor: color }, style]}
    />
  );
}
