import {UserRole, USER_ROLES} from '../models/user';
import {PERMISSIONS} from './permissions';
import type {Permission} from './permissions';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [USER_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [USER_ROLES.PRINCIPAL]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.STUDENTS_DELETE,

    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.TEACHERS_CREATE,
    PERMISSIONS.TEACHERS_UPDATE,
    PERMISSIONS.TEACHERS_DELETE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.EXAMS_MANAGE,

    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_MANAGE,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  [USER_ROLES.TEACHER]: [
    PERMISSIONS.STUDENTS_VIEW,

    PERMISSIONS.TEACHERS_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.EXAMS_VIEW,

    PERMISSIONS.RESULTS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  [USER_ROLES.STUDENT]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.RESULTS_VIEW,
  ],
};